### ISSUE TITLE
Add NLP related datasets

### ISSUE THREAD

**Issue by seanmor5** [elixir-nx/scidata#11]
With the addition of RNNs in Axon, I'd like to start adding some examples of using them in practice. @t-rutten would you be open to adding some NLP related datasets to the repository?

**Comment by t-rutten** [comment]
I'd be happy to add some @seanmor5! Do you have a few in mind that you think we should start with?

**Comment by seanmor5** [comment]
@t-rutten I was thinking IMDB Reviews and maybe some of the WMT language pairs datasets to start?
