### ISSUE TITLE
`StbImage` is undefined

### ISSUE THREAD

**Issue by alisinabh** [elixir-nx/scidata#31]
Hey :wave: 

I was trying to fidget with Nx and Axon today but it seems like the new `0.1.6` release is broken (Released just today) due to a missing struct called `StbImage`.

```
== Compilation error in file lib/scidata/caltech101.ex ==
** (CompileError) lib/scidata/caltech101.ex:153: StbImage.__struct__/0 is undefined, cannot expand struct StbImage. Make sure the struct name is correct. If the struct name exists and is correct but it still cannot be found, you likely have cyclic module usage in your code
    (elixir 1.13.4) expanding macro: Kernel.|>/2
```

Thank you for the great work :+1:

**Comment by josevalim** [comment]
My bad, I should have caught this and Elixir should have a better mechanism for testing compilation without optional dependencies. A new version is out!
